// <auto-generated />
using System;
using BugTicketingDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugTicketingDAL.Migrations
{
    [DbContext(typeof(BugTicketingContext))]
    [Migration("20250430003547_m-06")]
    partial class m06
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BugTicketingDAL.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BugId");

                    b.HasIndex("UserId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("BugTicketingDAL.Bug", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("BugTicketingDAL.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BugTicketingDAL.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "711a4a71-6a79-4c67-a5ff-7d38d6254a90",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20081146-a801-4276-a6de-90cfad6482cb",
                            Email = "MohamedEltabei@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MOHAMEDELTABEI@GMAIL.COM",
                            NormalizedUserName = "MOHAMEDELTABEI",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbBRmKhMQgMjXnpWE7kV5XW1EJTM1VUyaPHN/83fTdH7FF0F4TPCfPO7LayX4VgiQ==",
                            SecurityStamp = "d66b27d9-be5e-4a6e-8d32-1ebbe1209c73",
                            TwoFactorEnabled = false,
                            UserName = "MohamedEltabei"
                        },
                        new
                        {
                            Id = "7a8bf7b6-4979-4729-bd78-80c1f39aad34",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "15968bc9-945c-491b-8926-c33725488e4d",
                            Email = "KarimHelmy@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KARIMHELMY@GMAIL.COM",
                            NormalizedUserName = "KARIMHELMY",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbBRmKhMQgMjXnpWE7kV5XW1EJTM1VUyaPHN/83fTdH7FF0F4TPCfPO7LayX4VgiQ==",
                            SecurityStamp = "b2e99ab2-b261-438a-b9bf-3428da1a1e9e",
                            TwoFactorEnabled = false,
                            UserName = "KarimHelmy"
                        },
                        new
                        {
                            Id = "8f4b2288-bff8-4030-927e-e32bfdc9f90f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9db81390-5c91-4ab8-ad53-c158cf5fb130",
                            Email = "BasemAtia@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASEMATIA@GMAIL.COM",
                            NormalizedUserName = "BASEMATIA",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbBRmKhMQgMjXnpWE7kV5XW1EJTM1VUyaPHN/83fTdH7FF0F4TPCfPO7LayX4VgiQ==",
                            SecurityStamp = "f7833d18-b3a1-4ebf-b0ad-680f3dfb7be0",
                            TwoFactorEnabled = false,
                            UserName = "BasemAtia"
                        },
                        new
                        {
                            Id = "981fec6c-2d2a-4843-99bf-a5f9d4baf85b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21df4f63-ae4b-4de9-a2f1-7a4b2f028e87",
                            Email = "OmerAraby@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OMERARABY@GMAIL.COM",
                            NormalizedUserName = "OMERARABY",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbBRmKhMQgMjXnpWE7kV5XW1EJTM1VUyaPHN/83fTdH7FF0F4TPCfPO7LayX4VgiQ==",
                            SecurityStamp = "3a7d3936-5157-42ca-95fc-b85e03ede5a4",
                            TwoFactorEnabled = false,
                            UserName = "OmerAraby"
                        },
                        new
                        {
                            Id = "a23bb53a-7c52-4f13-8000-188ad242f04e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "15ca0019-f57e-418d-a1ef-3b91ce1279ad",
                            Email = "HaniAbdo@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HANIABDO@GMAIL.COM",
                            NormalizedUserName = "HANIABDO",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbBRmKhMQgMjXnpWE7kV5XW1EJTM1VUyaPHN/83fTdH7FF0F4TPCfPO7LayX4VgiQ==",
                            SecurityStamp = "baea035c-8f2c-4d5c-9972-72092c40044b",
                            TwoFactorEnabled = false,
                            UserName = "HaniAbdo"
                        },
                        new
                        {
                            Id = "e6c01d4f-bc6a-4fc3-afe3-62de02997dcf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f483a3ef-4d79-4b53-b0c9-34bc6fe74b31",
                            Email = "AlaaEisa@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALAAEISA@GMAIL.COM",
                            NormalizedUserName = "ALAAEISA",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbBRmKhMQgMjXnpWE7kV5XW1EJTM1VUyaPHN/83fTdH7FF0F4TPCfPO7LayX4VgiQ==",
                            SecurityStamp = "332de8d3-301c-49dd-a11b-78ab7e8dd0d4",
                            TwoFactorEnabled = false,
                            UserName = "AlaaEisa"
                        });
                });

            modelBuilder.Entity("BugTicketingDAL.UserBug", b =>
                {
                    b.Property<Guid>("BugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BugId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBugs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b172061-cc4b-416d-8559-4dcb240cd012",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4179d4b9-6aa8-4e27-8293-9fd69b331e8a",
                            Name = "Developer",
                            NormalizedName = "DEVELOPER"
                        },
                        new
                        {
                            Id = "bcd832ec-cae3-4b7b-baa6-f9f02b9858c0",
                            Name = "Tester",
                            NormalizedName = "TESTER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "711a4a71-6a79-4c67-a5ff-7d38d6254a90",
                            RoleId = "4179d4b9-6aa8-4e27-8293-9fd69b331e8a"
                        },
                        new
                        {
                            UserId = "a23bb53a-7c52-4f13-8000-188ad242f04e",
                            RoleId = "4179d4b9-6aa8-4e27-8293-9fd69b331e8a"
                        },
                        new
                        {
                            UserId = "7a8bf7b6-4979-4729-bd78-80c1f39aad34",
                            RoleId = "4179d4b9-6aa8-4e27-8293-9fd69b331e8a"
                        },
                        new
                        {
                            UserId = "7a8bf7b6-4979-4729-bd78-80c1f39aad34",
                            RoleId = "bcd832ec-cae3-4b7b-baa6-f9f02b9858c0"
                        },
                        new
                        {
                            UserId = "981fec6c-2d2a-4843-99bf-a5f9d4baf85b",
                            RoleId = "bcd832ec-cae3-4b7b-baa6-f9f02b9858c0"
                        },
                        new
                        {
                            UserId = "8f4b2288-bff8-4030-927e-e32bfdc9f90f",
                            RoleId = "0b172061-cc4b-416d-8559-4dcb240cd012"
                        },
                        new
                        {
                            UserId = "e6c01d4f-bc6a-4fc3-afe3-62de02997dcf",
                            RoleId = "0b172061-cc4b-416d-8559-4dcb240cd012"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BugTicketingDAL.Attachment", b =>
                {
                    b.HasOne("BugTicketingDAL.Bug", "Bug")
                        .WithMany("Attachments")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTicketingDAL.User", "User")
                        .WithMany("Attachments")
                        .HasForeignKey("UserId");

                    b.Navigation("Bug");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BugTicketingDAL.Bug", b =>
                {
                    b.HasOne("BugTicketingDAL.Project", "Project")
                        .WithMany("Bugs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugTicketingDAL.Project", b =>
                {
                    b.HasOne("BugTicketingDAL.User", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("BugTicketingDAL.UserBug", b =>
                {
                    b.HasOne("BugTicketingDAL.Bug", "Bug")
                        .WithMany("UserBugs")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTicketingDAL.User", "User")
                        .WithMany("UserBugs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bug");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BugTicketingDAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BugTicketingDAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTicketingDAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BugTicketingDAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BugTicketingDAL.Bug", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("UserBugs");
                });

            modelBuilder.Entity("BugTicketingDAL.Project", b =>
                {
                    b.Navigation("Bugs");
                });

            modelBuilder.Entity("BugTicketingDAL.User", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ManagedProjects");

                    b.Navigation("UserBugs");
                });
#pragma warning restore 612, 618
        }
    }
}
